### ISSUE TITLE
Error: TemplateLayoutPathResolver directory does not exist for layouts/base.njk: _includes

### ISSUE THREAD

**Issue by TedGoas** [danfascia/tai11s#12]
Hi there, thanks for putting the project together, I'm excited to use this as a starter template for my next project. But I'm having trouble installing it.

I cloned the repo, `npm install`'d, and everything seemed to complete successfully. However when I run `npm run dev` I get the following error.

Is this something you've encountered before? Something wrong with my local environment? Any ideas for me to try?

---

```
npm run dev

> tai11s@1.0.0 dev
> cross-env NODE_ENV=development npm-run-all clean styles:dev scripts:dev eleventy:default --parallel eleventy:watch serve --print-label

[clean           ] 
[clean           ] > tai11s@1.0.0 clean
[clean           ] > rm -rf dist
[clean           ] 
[styles:dev      ] 
[styles:dev      ] > tai11s@1.0.0 styles:dev
[styles:dev      ] > node-sass src/styles/ --output dist/styles/ --source-map true --source-map-contents true && postcss ./dist/styles/*.css --replace
[styles:dev      ] 
[styles:dev      ] Rendering Complete, saving .css file...
[styles:dev      ] Wrote Source Map to /Users/tedgoas/Documents/GitHub/Dante/dist/styles/index.css.map
[styles:dev      ] Wrote CSS to /Users/tedgoas/Documents/GitHub/Dante/dist/styles/index.css
[styles:dev      ] Wrote 1 CSS files to /Users/tedgoas/Documents/GitHub/Dante/dist/styles/
[scripts:dev     ] 
[scripts:dev     ] > tai11s@1.0.0 scripts:dev
[scripts:dev     ] > webpack --mode=development
[scripts:dev     ] 
[scripts:dev     ] Hash: 57a63860d4bcc17ee2f9
[scripts:dev     ] Version: webpack 4.31.0
[scripts:dev     ] Time: 259ms
[scripts:dev     ] Built at: 02/25/2021 8:40:14 PM
[scripts:dev     ]    Asset      Size  Chunks             Chunk Names
[scripts:dev     ] index.js  4.66 KiB    main  [emitted]  main
[scripts:dev     ] Entrypoint main = index.js
[scripts:dev     ] [./src/scripts/index.js] 73 bytes {main} [built]
[scripts:dev     ] [./src/scripts/modules/list.js] 62 bytes {main} [built]
[eleventy:default] 
[eleventy:default] > tai11s@1.0.0 eleventy:default
[eleventy:default] > eleventy
[eleventy:default] 
[eleventy:default] Problem writing Eleventy templates: (more in DEBUG output)
[eleventy:default] > TemplateLayoutPathResolver directory does not exist for layouts/base.njk: _includes (Error):
[eleventy:default]     Error: TemplateLayoutPathResolver directory does not exist for layouts/base.njk: _includes
[eleventy:default]         at TemplateLayoutPathResolver.findFileName (/Users/tedgoas/Documents/GitHub/Dante/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:96:13)
[eleventy:default]         at TemplateLayoutPathResolver.init (/Users/tedgoas/Documents/GitHub/Dante/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:61:28)
[eleventy:default]         at new TemplateLayoutPathResolver (/Users/tedgoas/Documents/GitHub/Dante/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:15:10)
[eleventy:default]         at new TemplateLayout (/Users/tedgoas/Documents/GitHub/Dante/node_modules/@11ty/eleventy/src/TemplateLayout.js:15:24)
[eleventy:default]         at Function.getTemplate (/Users/tedgoas/Documents/GitHub/Dante/node_modules/@11ty/eleventy/src/TemplateLayout.js:38:16)
[eleventy:default]         at Template.getData (/Users/tedgoas/Documents/GitHub/Dante/node_modules/@11ty/eleventy/src/Template.js:217:37)
[eleventy:default]         at async Template.getTemplateMapEntries (/Users/tedgoas/Documents/GitHub/Dante/node_modules/@11ty/eleventy/src/Template.js:668:16)
[eleventy:default]         at async TemplateMap.add (/Users/tedgoas/Documents/GitHub/Dante/node_modules/@11ty/eleventy/src/TemplateMap.js:28:21)
[eleventy:default]         at async Promise.all (index 1)
[eleventy:default]         at async TemplateWriter._createTemplateMap (/Users/tedgoas/Documents/GitHub/Dante/node_modules/@11ty/eleventy/src/TemplateWriter.js:123:3)
[eleventy:default] Processed 0 files in 0.13 seconds
ERROR: "eleventy:default" exited with 1.
```

<img width="1262" alt="Screen Shot 2021-02-25 at 8 44 27 PM" src="https://user-images.githubusercontent.com/1172461/109243135-635b3700-77aa-11eb-895c-31c7fbfe3600.png">

**Comment by TedGoas** [comment]
I think I resolved this. When I forked this project, apparently the invisible files in the root (most notably `.eleventy.js`) didn't copy over. After adding those back, the project now compiles.
